services:
  redis:
    image: redis:5-alpine
    volumes:
      - ./docker/data/redis:/data
    restart: unless-stopped
    ports:
      - "63791:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "55401:5540"
    depends_on:
      - redis
